version: "3"


services:
  app_db:
    image: postgres:alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db